### ISSUE TITLE
RPI3: Running on Docker

### ISSUE THREAD

**Issue by mplacona** [fphammerle/switchbot-mqtt#19] opened 2020-12-01 11:00 UTC
Heya! Thank you for the library! I think it will do exactly what I need it to do once I figure out how to use it correctly.

Using the readme and trying o run with an RPI3 cause an error though because I think the latest tag is AMD64 instead of ARM. I went ahead and changed the docker-compose file to use the tag `0.5.0-arm64` and even though this time I managed to pull the container correctly, it gives me a:

`switchbot-mqtt    | standard_init_linux.go:211: exec user process caused "exec format error"`

I thought this was because of the architecture (hence changing on ARM64) but seems not.

I tried using it via `pip install` too though my preference is always for Docker but found a couple of things:

If I send "ON" or "OFF" to `homeassistant/switch/switchbot/{{mac}}/set` I most times get no response, and sometimes get:

```
5:36:99:fd:ef:6a/set payload=b'OFF'
2020-12-01T10:58:35+0000:DEBUG:Sending command to switchbot 570102
2020-12-01T10:58:35+0000:DEBUG:Connecting to Switchbot...
2020-12-01T10:58:37+0000:DEBUG:Connected to Switchbot.
2020-12-01T10:58:37+0000:DEBUG:Prepare to send
```

And it never really goes anywhere or does anything. I am sure I am probably missing something here but would appreciate any support. Also, is there a way to implement "PRESS" into this too? I think "pySwitchbot" which is the library you use here also supports it.

Thanks again

**Comment by fphammerle** [comment] 2020-12-01 11:08
Hi,

as far as I know, only RPI4 support ARM64 images. RPI3 requires a ARMv7 image.
I'll build a new image and send you the tag as soon as it's ready

Let's debug the sending issue after the docker image works

**Comment by mplacona** [comment] 2020-12-01 12:21
> Hi,
> 
> as far as I know, only RPI4 support ARM64 images. RPI3 requires a ARMv7 image.
> I'll build a new image and send you the tag as soon as it's ready
> 
> Let's debug the sending issue after the docker image works

I modified `BASE_IMAGE` to `arm32v7/alpine:3.10` and built a new image and can now run this in Docker inside the Pi. Happy to send a PR if you like.

However, I still observe the same behaviour where sending ON or OFF results in:

```
switchbot-mqtt    | 2020-12-01T12:18:25+0000:DEBUG:received topic=homeassistant/switch/switchbot/{{MAC}}/set payload=b'ON'
switchbot-mqtt    | 2020-12-01T12:18:25+0000:DEBUG:Sending command to switchbot 570101
switchbot-mqtt    | 2020-12-01T12:18:25+0000:DEBUG:Connecting to Switchbot...
switchbot-mqtt    | 2020-12-01T12:18:26+0000:DEBUG:Connected to Switchbot.
switchbot-mqtt    | 2020-12-01T12:18:26+0000:DEBUG:Prepare to send
```

**Comment by fphammerle** [comment] 2020-12-01 12:34
Could you maybe also check if the tag `fphammerle/switchbot-mqtt:0.5.0-armv6` works?
(fingerprint: `sha256:7fc91ece5da204d381a394c049afcf6bde6da780fb14aff677e1458ada1975ad `)

I just built it on RPI1 (ARMv6) as I don't have a RPI3.
The ARMv6 image should be compatible with RPI1, RPI2 and RPI3.

I think a switch to `FROM arm32v7/alpine:3.10` is not necessary as the standard alpine image already supports ARM
(see https://hub.docker.com/layers/alpine/library/alpine/3.12/images/sha256-4e01ddea8def856ba9fee17668fa0b2e45a8bc78127b7ab6cf921f6d6fd86ac9?context=explore under OS/ARCH)

---

Regarding the second issue:
Have you maybe tried using `pySwitchbot` directly?
I wonder whether the problem is caused by `switchbot-mqtt`, `pySwitchbot`, or the bluetooth stack.

**Comment by fphammerle** [comment] 2020-12-01 12:39
Does the following python script activate your switchbot button?
```python
import switchbot
switchbot_device = switchbot.Switchbot(mac="aa:bb:cc:dd:ee:ff")
switchbot_device.turn_on():
# or
switchbot_device.press()
```

**Comment by mplacona** [comment] 2020-12-01 21:18
Sounds like that might be the problem because using the code above also hangs. So it got me thinking that maybe I have something wrong with my setup.

I looked at an alternative and found [python-host](https://github.com/OpenWonderLabs/python-host) which when executed with the Python 3 file works as expected.

**Comment by fphammerle** [comment] 2020-12-01 21:23
Did you run `python-host` as `root` / via `sudo` ?

If yes, could you maybe retry running
```
import switchbot
switchbot_device = switchbot.Switchbot(mac="aa:bb:cc:dd:ee:ff")
switchbot_device.turn_on():
```
also as `root`?

Maybe an unprivileged user does not have permission to use bluetooth on your setup.

**Comment by mplacona** [comment] 2020-12-01 21:26
Hey, yes I had to run python-host as root. I thought I'd give it a go with this too as root (w/ sudo) but no dice. 

Also, just to close the loop on the docker image, I did try the tag you mentioned and it run ok, though I still get the same result. i.e. it just hangs

**Comment by fphammerle** [comment] 2020-12-01 21:31
> Also, just to close the loop on the docker image, I did try the tag you mentioned and it run ok, though I still get the same result. i.e. it just hangs

Thanks for trying!

> Hey, yes I had to run python-host as root. I thought I'd give it a go with this too as root (w/ sudo) but no dice.

Does `sudo journalctl -f` maybe show an error message when executing `switchbot_device.turn_on()`?

**Comment by mplacona** [comment] 2020-12-01 21:35
No errors. This is so weird!

```
Dec 01 21:34:58 pigateway sudo[16030]:       pi : TTY=pts/2 ; PWD=/home/pi/switchbot-mqtt ; USER=root ; COMMAND=/usr/bin/python test.py
Dec 01 21:34:58 pigateway sudo[16030]: pam_unix(sudo:session): session opened for user root by pi(uid=0)
```

**Comment by fphammerle** [comment] 2020-12-01 21:47
Thanks for checking the log, really strange! :/

`Prepare to send` is the last log message you see, right?
I just checked the source code of `pySwitchbot`:
Shortly after `Prepare to send` should follow `Sending command, {key}`:
https://github.com/Danielhiversen/pySwitchbot/blob/0.8.0/switchbot/__init__.py#L75

So I assume one of these two lines fails:
```python
        hand_service = self._device.getServiceByUUID(UUID)
        hand = hand_service.getCharacteristics(HANDLE)[0]
```

Sorry, I am out of ideas currently.
If you can't find any alternative MQTT-based solution, I would suggest opening an issue at https://github.com/Danielhiversen/pySwitchbot/issues .
Maybe they had the same issue before

**Comment by fphammerle** [comment] 2021-10-16 13:24
Closing as this bug is caused somewhere in `pySwitchbot` or `bluepy`

**Closed by fphammerle** 2021-10-16 13:24 UTC
Labels: bug
